name: Release Please

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR merge status
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "PR merged: ${{ github.event.pull_request.merged }}"
          echo "PR state: ${{ github.event.pull_request.state }}"
          echo "Base branch: ${{ github.base_ref }}"
          echo "Head branch: ${{ github.head_ref }}"

      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: python
          package-name: calculator-api
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          include-v-in-tag: true
